Repository Devops-2022-Group-R/itu-minitwit, pull requests merged in 2022-04, with the labels that each got.

#92 Flagtool/add authorization
  src/controllers/controllers.go
  src/controllers/flag_tool.go
  src/test/controllers/flag_tool_test.go
Labels: minor

#95 Add logging
  .infrastructure/kubernetes/backend/.gitignore
  .infrastructure/kubernetes/backend/backend-deployment.yaml
  .infrastructure/kubernetes/backend/backend-secrets-unsealed.yaml
  .infrastructure/kubernetes/backend/backend-secrets.yaml
  .infrastructure/kubernetes/backend/database-secret.yaml
  .infrastructure/kubernetes/backend/database-storage.yaml
  .infrastructure/kubernetes/backend/database.yaml
  .infrastructure/kubernetes/backend/mycert.pem
  .infrastructure/kubernetes/clustercert.pem
  .infrastructure/kubernetes/logging/elasticsearch.yml
  .infrastructure/kubernetes/logging/fluentd-config.yml
  .infrastructure/kubernetes/logging/fluentd.yml
  .infrastructure/kubernetes/logging/kibana.yml
  .infrastructure/kubernetes/logging/logging-namespace.yaml
  .infrastructure/kubernetes/logging/testapp.yml
  .infrastructure/kubernetes/monitoring/monitoring-grafana-deployment.yaml
  .infrastructure/kubernetes/monitoring/monitoring-prometheus-deployment.yaml
  .infrastructure/kubernetes/monitoring/monitoring-storage.yaml
  .infrastructure/kubernetes/networking/cluster-issuer-prod.yaml
  .infrastructure/kubernetes/networking/cluster-issuer-staging.yaml
  .infrastructure/kubernetes/networking/external-dns-secret.json
  .infrastructure/kubernetes/networking/network-namespace.yaml
  .infrastructure/kubernetes/storage/.gitignore
  .infrastructure/kubernetes/storage/azure-cloud-provider.yaml
  .infrastructure/kubernetes/storage/storage-class.yaml
  .infrastructure/main.tf
  notes/complete-deployment.md
  notes/session09.md
  src/controllers/controllers.go
  src/database/message-repository.go
  src/database/user-repository.go
  src/internal/logging.go
  src/main.go
Labels: enhancement, minor

#103 Fix kubernetes deployment
  .circleci/config.yml
  .infrastructure/.tfvars
  .infrastructure/kubernetes/apply.sh
  .infrastructure/kubernetes/networking/.gitignore
  .infrastructure/kubernetes/networking/external-dns-secret.json
  .infrastructure/main.tf
  .infrastructure/variables.tf
Labels: enhancement, patch
