Repository Devops-2022-Group-R/itu-minitwit, pull requests merged in 2022-03, with the labels that each got.

#52 Add attempt at auto-creating releases
  .circleci/config.yml
Labels: minor

#51 Rewrite latest flow and fix open connections
  src/database/database.go
  src/database/gorm_latest_repository.go
  src/database/latest_repository.go
Labels: bug, patch

#58 Port flagtool
  src/controllers/controllers.go
  src/controllers/flag_tool.go
  src/database/gorm-message-repository.go
  src/database/message-repository.go
  src/test/controllers/flag_tool_test.go
Labels: minor

#62 Unified logging
  src/controllers/controllers.go
  src/database/database.go
  src/internal/logging.go
  src/main.go
Labels: enhancement, minor

#61 Add monitoring using Prometheus and Grafana
  .circleci/config.yml
  .infrastructure/main.tf
  Makefile
  go.mod
  go.sum
  monitoring/docker-compose.yml
  monitoring/grafana/Dockerfile
  monitoring/grafana/provisioning/dashboards/dashboards.yml
  monitoring/grafana/provisioning/dashboards/minitwit-dashboard.json
  monitoring/grafana/provisioning/datasources/datasources.yml
  monitoring/prometheus/Dockerfile
  monitoring/prometheus/prometheus-dev.yml
  monitoring/prometheus/prometheus-prod.yml
  notes/session06.md
  notes/session06_prep.md
  src/controllers/controllers.go
  src/controllers/register.go
  src/database/gorm-user-repository.go
  src/database/user-repository.go
  src/main.go
  src/monitoring/monitoring.go
Labels: enhancement, minor

#72 Add more precise monitoring
  go.mod
  go.sum
  monitoring/grafana/provisioning/dashboards/minitwit-dashboard.json
  src/controllers/controllers.go
  src/monitoring/monitoring.go
Labels: enhancement, minor

#63 Centralized error handling
  src/controllers/controllers.go
  src/controllers/flag_tool.go
  src/controllers/follow.go
  src/controllers/latest.go
  src/controllers/login.go
  src/controllers/message.go
  src/controllers/register.go
  src/controllers/user-util.go
  src/internal/error-handling.go
  src/internal/errors.go
Labels: enhancement, minor

#77 Add indexes to the database
  src/database/message-repository.go
  src/database/user-repository.go
Labels: enhancement, patch

#76 Remove flag tool and unused variables
  main.go
  requirements.txt
  scripts/control.sh
  scripts/flag_tool
  scripts/flag_tool.c
  src/custom/logging.go
  src/structs.go
Labels: enhancement, patch

#79 Add lint job to Circle CI
  .circleci/config.yml
  Makefile
  src/controllers/follow.go
  src/controllers/latest.go
  src/controllers/message.go
  src/controllers/user-util.go
  src/database/database.go
  src/internal/error-handling.go
  src/internal/logging.go
  src/main.go
  src/password/password.go
  src/test/controllers/controllers_test.go
Labels: code, patch

#82 Add missing auto-approve to terraform apply
  .circleci/config.yml
Labels: bug, patch

#73 Add static analysis
  .circleci/config.yml
Labels: enhancement

#84 Use Alpine during runtime in Docker image
  Dockerfile
Labels: enhancement, patch

#86 Make gocyclo fail build on issues
  .circleci/config.yml
Labels: bug
