Repository Devops-2022-Group-R/itu-minitwit, pull requests merged in 2022-02, with the labels that each got.

#2 Add VS Code devcontainer for Go and SQLite
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: code

#5 Containerize application
  Dockerfile
  notes/session02.md
  readme.md
Labels: enhancement

#22 Tested message controller
  src/controllers/message.go
  src/test/controllers/message_test.go
Labels: documentation, enhancement

#26 Remove templates
  src/static/style.css
  src/templates/layout.html
  src/templates/login.html
  src/templates/register.html
  src/templates/timeline.html
Labels: enhancement

#25 Created feed endpoint
  src/controllers/controllers.go
  src/controllers/message.go
Labels: enhancement

#27 Login middleware
  src/controllers/consts.go
  src/controllers/controllers.go
  src/controllers/follow.go
  src/controllers/login.go
  src/controllers/message.go
  src/test/controllers/follow_test.go
  src/test/controllers/message_test.go
Labels: enhancement

#31 Cleanup and tests
  src/controllers/follow.go
  src/database/database.go
  src/database/utils.go
  src/test/controllers/controllers_test.go
  src/test/controllers/follow_test.go
  src/test/controllers/latest_test.go
  src/test/controllers/login_test.go
  src/test/controllers/message_test.go
  src/test/controllers/register_test.go
Labels: enhancement

#41 Add .circleci/config.yml
  .circleci/config.yml
Labels: code
